/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animalhome.UI;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.HashSet;

/**
 *
 * @author cris
 */
public final class UICliente extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public UICliente() {
        initComponents();
        this.setIconImage(getIconImage());
        setExtendedState(MAXIMIZED_BOTH);
        Mascotas.setVisible(true);
    }
    
    public void componentes(){
      
    }
    
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("ImagenesUiCliente/AH2.png"));
    return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mascotas = new javax.swing.JPanel();
        Apartar = new javax.swing.JPanel();
        Tienda = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn7 = new javax.swing.JLabel();
        btn2 = new javax.swing.JLabel();
        btn8 = new javax.swing.JLabel();
        btn9 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        Gen2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ContenerC1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelRG1 = new animalhome.metodos.PanelRG();
        imagenRescala1 = new animalhome.metodos.ImagenRescala();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Gen3 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JLabel();
        botonMod1 = new animalhome.metodos.BotonMod();
        botonMantenerMod1 = new animalhome.metodos.BotonMantenerMod();
        botonMantenerMod2 = new animalhome.metodos.BotonMantenerMod();
        botonMantenerMod3 = new animalhome.metodos.BotonMantenerMod();
        jPanel7 = new javax.swing.JPanel();

        Mascotas.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout MascotasLayout = new javax.swing.GroupLayout(Mascotas);
        Mascotas.setLayout(MascotasLayout);
        MascotasLayout.setHorizontalGroup(
            MascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        MascotasLayout.setVerticalGroup(
            MascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        Apartar.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout ApartarLayout = new javax.swing.GroupLayout(Apartar);
        Apartar.setLayout(ApartarLayout);
        ApartarLayout.setHorizontalGroup(
            ApartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        ApartarLayout.setVerticalGroup(
            ApartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        Tienda.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout TiendaLayout = new javax.swing.GroupLayout(Tienda);
        Tienda.setLayout(TiendaLayout);
        TiendaLayout.setHorizontalGroup(
            TiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        TiendaLayout.setVerticalGroup(
            TiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));

        btn7.setBackground(new java.awt.Color(51, 102, 255));
        btn7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_shop_43px.png"))); // NOI18N
        btn7.setText("Tienda");
        btn7.setOpaque(true);
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(32, 76, 209));
        btn2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_animal_shelter_41px.png"))); // NOI18N
        btn2.setText("Mascotas");
        btn2.setToolTipText("");
        btn2.setOpaque(true);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/exit_32px.png"))); // NOI18N
        btn8.setText("Salir");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(51, 102, 255));
        btn9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_veterinarian_41px.png"))); // NOI18N
        btn9.setText("Apartar Cita");
        btn9.setOpaque(true);
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("Conectado");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        Nombre2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(204, 204, 204));
        Nombre2.setText("Nombre del Usuario");
        Nombre2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Nombre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre2MouseClicked(evt);
            }
        });

        Gen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_male_user_43px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Gen2)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gen2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9))
                    .addComponent(Nombre2))
                .addGap(71, 71, 71)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(60, 86, 225));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/AH3.png"))); // NOI18N
        jLabel3.setText("Animal Home");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 30));

        ContenerC1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenerC1Layout = new javax.swing.GroupLayout(ContenerC1);
        ContenerC1.setLayout(ContenerC1Layout);
        ContenerC1Layout.setHorizontalGroup(
            ContenerC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenerC1Layout.setVerticalGroup(
            ContenerC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenerC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContenerC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panelRG1.setColor1(new java.awt.Color(0, 0, 51));
        panelRG1.setColor2(new java.awt.Color(9, 43, 225));
        panelRG1.setMinimumSize(new java.awt.Dimension(800, 40));
        panelRG1.setPreferredSize(new java.awt.Dimension(800, 30));
        panelRG1.setPunto1X(800);
        panelRG1.setPunto1Y(50);
        panelRG1.setPunto2X(30);
        panelRG1.setRedonabajoderrecha(0);
        panelRG1.setRedonabajoizquierda(0);
        panelRG1.setRedonarribaderrecha(0);
        panelRG1.setRedonarribaizquierda(0);

        imagenRescala1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/AH3.png"))); // NOI18N
        imagenRescala1.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Animal Home");

        javax.swing.GroupLayout panelRG1Layout = new javax.swing.GroupLayout(panelRG1);
        panelRG1.setLayout(panelRG1Layout);
        panelRG1Layout.setHorizontalGroup(
            panelRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRG1Layout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(imagenRescala1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRG1Layout.setVerticalGroup(
            panelRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRG1Layout.createSequentialGroup()
                .addGroup(panelRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagenRescala1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jPanel1.add(panelRG1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(9, 43, 225));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 449));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("Conectado");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        Gen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_male_user_43px.png"))); // NOI18N

        Nombre3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Nombre3.setForeground(new java.awt.Color(204, 204, 204));
        Nombre3.setText("Nombre del Usuario");
        Nombre3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Nombre3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre3MouseClicked(evt);
            }
        });

        botonMod1.setBackground(new java.awt.Color(9, 43, 225));
        botonMod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/exit_32px.png"))); // NOI18N
        botonMod1.setColor1(new java.awt.Color(7, 37, 196));
        botonMod1.setColor2(new java.awt.Color(0, 102, 153));
        botonMod1.setColor3(new java.awt.Color(0, 51, 204));
        botonMod1.setDegrade(30);
        botonMod1.setRedonabajoderrecha(30);
        botonMod1.setRedonabajoizquierda(30);
        botonMod1.setRedonarribaderrecha(30);
        botonMod1.setRedonarribaizquierda(30);
        botonMod1.setSizeSpeed(10.0F);

        buttonGroup1.add(botonMantenerMod1);
        botonMantenerMod1.setSelected(true);
        botonMantenerMod1.setColorfont(new java.awt.Color(0, 0, 0));
        botonMantenerMod1.setFondo(new java.awt.Color(9, 43, 225));
        botonMantenerMod1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        botonMantenerMod1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonMantenerMod1.setHover(new java.awt.Color(255, 255, 255));
        botonMantenerMod1.setImagenClick(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_shop_43px_3.png"))); // NOI18N
        botonMantenerMod1.setImagenInicio(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_shop_43px.png"))); // NOI18N
        botonMantenerMod1.setLabel("Tienda");
        botonMantenerMod1.setLetra(new java.awt.Color(255, 255, 255));
        botonMantenerMod1.setRedonabajoderrecha(0);
        botonMantenerMod1.setRedonabajoizquierda(30);
        botonMantenerMod1.setRedonarribaderrecha(0);
        botonMantenerMod1.setRedonarribaizquierda(30);

        buttonGroup1.add(botonMantenerMod2);
        botonMantenerMod2.setColorfont(new java.awt.Color(0, 0, 0));
        botonMantenerMod2.setFondo(new java.awt.Color(9, 43, 225));
        botonMantenerMod2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        botonMantenerMod2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonMantenerMod2.setHover(new java.awt.Color(255, 255, 255));
        botonMantenerMod2.setImagenClick(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_shop_43px_3.png"))); // NOI18N
        botonMantenerMod2.setImagenInicio(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_shop_43px.png"))); // NOI18N
        botonMantenerMod2.setLabel("Tienda");
        botonMantenerMod2.setLetra(new java.awt.Color(255, 255, 255));
        botonMantenerMod2.setRedonabajoderrecha(0);
        botonMantenerMod2.setRedonabajoizquierda(30);
        botonMantenerMod2.setRedonarribaderrecha(0);
        botonMantenerMod2.setRedonarribaizquierda(30);

        buttonGroup1.add(botonMantenerMod3);
        botonMantenerMod3.setColorfont(new java.awt.Color(0, 0, 0));
        botonMantenerMod3.setFondo(new java.awt.Color(9, 43, 225));
        botonMantenerMod3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        botonMantenerMod3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonMantenerMod3.setHover(new java.awt.Color(255, 255, 255));
        botonMantenerMod3.setImagenClick(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_shop_43px_3.png"))); // NOI18N
        botonMantenerMod3.setImagenInicio(new javax.swing.ImageIcon(getClass().getResource("/ImagenesUiCliente/icons8_shop_43px.png"))); // NOI18N
        botonMantenerMod3.setLabel("Tienda");
        botonMantenerMod3.setLetra(new java.awt.Color(255, 255, 255));
        botonMantenerMod3.setRedonabajoderrecha(0);
        botonMantenerMod3.setRedonabajoizquierda(30);
        botonMantenerMod3.setRedonarribaderrecha(0);
        botonMantenerMod3.setRedonarribaizquierda(30);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Gen3)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMantenerMod1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMantenerMod2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMantenerMod3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gen3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10))
                    .addComponent(Nombre3))
                .addGap(87, 87, 87)
                .addComponent(botonMantenerMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonMantenerMod2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonMantenerMod3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(botonMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Color Selec = new Color(255,255,255);
Color Unselec = new Color(51,102,255);    Color E = new Color(32,76,209);
    Color O = new Color(51,102,255);
    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseClicked

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseEntered

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void Nombre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void Nombre3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre3MouseClicked
    private static boolean VerificarRed() {
        try {
            final URL url = new URL("http://www.google.com");
            final URLConnection conn = url.openConnection();
            conn.connect();
            conn.getInputStream().close();
            return true;
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
        return false;
        }
    }
    public void MostrarConexion(){
        /*if(VerificarRed()==true){
            jLabel7.setForeground(new java.awt.Color(51, 255, 51));
            jLabel7.setText("Conectado");
            System.out.println("Con Red");
        }else{
            jLabel7.setForeground(Color.RED);
            jLabel7.setText("Desconectado");
            System.out.println("Sin Red");
        }*/
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Apartar;
    private javax.swing.JPanel ContenerC1;
    private javax.swing.JLabel Gen2;
    private javax.swing.JLabel Gen3;
    private javax.swing.JPanel Mascotas;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JPanel Tienda;
    private animalhome.metodos.BotonMantenerMod botonMantenerMod1;
    private animalhome.metodos.BotonMantenerMod botonMantenerMod2;
    private animalhome.metodos.BotonMantenerMod botonMantenerMod3;
    private animalhome.metodos.BotonMod botonMod1;
    private javax.swing.JLabel btn2;
    private javax.swing.JLabel btn7;
    private javax.swing.JLabel btn8;
    private javax.swing.JLabel btn9;
    private javax.swing.ButtonGroup buttonGroup1;
    private animalhome.metodos.ImagenRescala imagenRescala1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private animalhome.metodos.PanelRG panelRG1;
    // End of variables declaration//GEN-END:variables
}
